export const navLinks = [
    {
        id:1,
        url:"#home",
        label:"Home",
    },
    {
        id:2,
        url:"#destination",
        label:"Destination",
    },
    {
        id:3,
        url:"#hotels",
        label:"Dashboard",
    },
    {
        id:4,
        url:"#about",
        label:"About",
    },
    {
        id:5,
        url:"#news",
        label:"Blog",
    },
    {
        id:6,
        url:"#contact",
        label:"Contact",
    }
]